version: 2
jobs:
  test:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run: 
        name: Install dependencies
        command: |
          apt-get update && apt-get install -y wget zip unzip
      - run:
        name: Begin setup NOOBS
        command: |
          sh ./setup.sh
workflows:
  version: 2
  test_and_release:
    jobs:
      - test
