version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run: 
        name: Install dependencies
        command: |
          apt-get update && apt-get install -y wget zip unzip
      - run:
        name: Begin setup NOOBS
        command: |
          sh ./setup.sh
  release-latest:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
        name: Release artifacts
        command: |
          sh ./release.sh latest

workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - release-latest:
          filters:
            branches:
              only: master
