version: 2
jobs:
  test:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
        name: Install dependencies
        command: echo test
      - run:
        name: Begin setup NOOBS
        command: sh ./setup.sh

workflows:
  version: 2
  test_and_release:
    jobs:
      - test
