version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: apt-get update && apt-get install -y wget zip unzip ca-certificates
      - run:
          name: Begin setup NOOBS
          command: sh ./setup.sh
      - persist_to_workspace:
          root: .
          paths:
            - .
      
  release-latest:
    docker:
      - image: debian:stretch
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Check directory
          command: ls -l && pwd
      - run:
          name: Install dependencies
          command: apt-get update && apt-get install -y wget ca-certificates
      - run:
          name: Release artifacts
          command: sh ./release.sh latest

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release-latest:
          requires:
            - build
          filters:
            branches:
              only: master
