version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: apt-get update && apt-get install -y wget zip unzip
      - run:
          name: Begin setup NOOBS
          command: sh ./setup.sh

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release-latest:
          requires:
            - test
          filters:
            branches:
              only: master
